### ISSUE TITLE
can i help with c++ cause you suck

### ISSUE THREAD

**Issue by AndrewDisco** [SkylixGH/Elixor#5]

**Comment by AndrewDisco** [comment]
thats all thanks for visiting

andrew

**Comment by AndrewDisco** [comment]
Well I wouldn’t have said this but you used std namespace and still std::   :<

**Comment by XFaonAE** [comment]
AHHAAHAH, well i was migrating a ton of old code and quit some bits and thats leftover, if u wana make a PR go for it, dont add any new features tho
